export const SENDGRID_ID = {
  vi: 'd-9b174ed63d7244cf848583b2bc114005',
  en: 'd-f097b387143746beb35eb360bef59df0'
}

export const SENDGRID_ID_OLD = {
  vi: 'd-706255bb1f0a4e329826805f78a1572b',
  en: 'd-51e66f89753140f0a961d1cdb78ec3a9'
}

export const SENDGRID_ID_AMBER = {
  vi: 'd-50fec39415d84c03a7b09161220c8409',
  en: 'd-613f33288c774f11b305f0bae0680aaa'
}

export const HOSTNAME_CAPTCHA = ['coin98.com', 'coin98.net', 'marginatm.com', 'lunadex.com', 'amberblocks.com', 'amberblocks.c98staging.dev',
  'knowledge.c98staging.dev',
  'exchange.c98staging.dev',
  'dapps.c98staging.dev',
  'dapps.coin98.com',
  'exchange.coin98.com',
  'earn.coin98.com',
  'earn.c98staging.dev',
  'wallet.c98staging.dev',
  'markets.c98staging.dev',
  'portfolio.c98staging.dev',
  'wallet.coin98.com',
  'insights.c98staging.dev',
  'markets.coin98.com',
  'portfolio.coin98.com', 'amberblocks-preproduction.c98staging.dev', 'insights-preproduction.c98staging.dev'
]

export const COIN_IMAGE = {
  CUSDC98: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/CUSDC98.png',
  BTC: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/BTC.png',
  ETH: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ETH.png',
  ETHARB: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/arbitrum_eth.png',
  ETHA0X: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/arbitrum_xdai.png',
  OP: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/op.png',
  BOBA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/boba_eth.png',
  KCS: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/kucoin.png',
  BNB: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/BNBVer2.png',
  HT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/heco.png',
  TOMO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/Tomo.png',
  USDT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/USDT.jpg',
  AVAX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/avax.png',
  KSM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/kusama.png',
  NEAR: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/near.png',
  DOT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/dot.png',
  C98: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/coin98.png',
  TRX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/tron.png',
  CELO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/celo.png',
  SOL: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/solana.jpg',
  SRM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/serum.jpg',
  ATOM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/cosmos.png',
  RUNE: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/thor.png',
  LUNA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/terra.png',
  LUNA2: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/terra2.png',
  KAVA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/kava.png',
  SCRT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/secretNetwork.png',
  EGLD: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/elrond.png',
  XTZ: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/tezos.png',
  ONE: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/harmony.png',
  CFX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/conflux.png',
  AURORA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/aurora.png',

  BAND: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/band.png',
  FTM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/fantom.png',
  MATIC: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/polygon.png',
  XPRT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/persistance.png',
  XDAI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_xdai.png',
  KAI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_kardia.png',
  RON: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_ronin.png',
  OKT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_okex.png',
  GT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_gate.png',
  KLAY: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_klaytn.png',

  CRO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/CRO.png',
  BTT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/BTT.png',
  HNT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_hnt.png',
  FLOW: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_flow.png',
  THETA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/THETA.png',
  GLMR: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/GMLR.png',
  LAT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/LAT.png',
  TON: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/TON.png',
  TFUEL: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/TFUEL.png',
  ALGO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/algorand.png',
  CSPR: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/casper.png',
  FX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/fx.png'
}

export const MAIN_COIN_AMM = {
  [chainType.ether]: {
    chainId: 1,
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
    logoURI: COIN_IMAGE.ETH,
    address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
  },
  [chainType.binanceSmart]: {
    id: 'binancecoin',
    chainId: 56,
    name: 'BNB Token',
    symbol: 'BNB',
    decimals: 18,
    logoURI: COIN_IMAGE.BNB,
    address: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
  },
  [chainType.heco]: {
    id: 'huobi-token',
    chainId: 128,
    name: 'HT Token',
    symbol: 'HT',
    decimals: 18,
    logoURI: COIN_IMAGE.HT,
    address: '0x5545153CCFcA01fbd7Dd11C0b23ba694D9509A6F'
  },
  [chainType.matic]: {
    id: 'matic-network',
    chainId: 137,
    name: 'Matic',
    symbol: 'MATIC',
    decimals: 18,
    logoURI: COIN_IMAGE.MATIC,
    address: '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270'
  },
  [chainType.avax]: {
    id: 'avalanche-2',
    chainId: 43114,
    name: 'Avax',
    symbol: 'AVAX',
    decimals: 18,
    logoURI: COIN_IMAGE.AVAX,
    address: '0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7'
  },
  [chainType.fantom]: {
    id: 'fantom',
    chainId: 250,
    name: 'Fantom',
    symbol: 'FTM',
    decimals: 18,
    logoURI: COIN_IMAGE.FTM,
    address: '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83'
  },
  [chainType.kucoin]: {
    id: 'kucoin-shares',
    chainId: 321,
    name: 'KuCoin Chain',
    symbol: 'KCS',
    decimals: 18,
    logoURI: COIN_IMAGE.KCS,
    address: '0x4446Fc4eb47f2f6586f9fAAb68B3498F86C07521'
  },
  [chainType.celo]: {
    id: 'celo',
    chainId: 42220,
    name: 'Celo',
    symbol: 'Celo',
    decimals: 18,
    logoURI: COIN_IMAGE.CELO,
    address: '0x471EcE3750Da237f93B8E339c536989b8978a438'
  },
  [chainType.boba]: {
    id: 'ethereum',
    chainId: 288,
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
    logoURI: COIN_IMAGE.ETH,
    address: '0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000'
  },
  [chainType.solana]: {
    symbol: 'SOL'
  }
}

export const CHAIN_DATA = {
  multiChain: {
    isOther: true,
    isMnemonic: true,
    name: 'Multi-Chain',
    image: 'app_multi_chain',
    chain: chainType.multiChain,
    trcName: 'All Blockchain'
  },
  customCreate: {
    isOther: true,
    name: 'Custom Network',
    image: 'app_custom_network',
    chain: chainType.customCreate,
    trcName: 'Create Custom Network'
  },
  custom: {
    isOther: true,
    name: 'Custom Network',
    image: 'app_box',
    chain: chainType.custom,
    trcName: 'Custom Network'
  },
  bitcoin: {
    numLoad: 5,
    isFee: true,
    isMnemonic: true,
    image: 'app_bitcoin',
    id: 'bitcoin',
    name: 'Bitcoin',
    shortName: 'Bitcoin',
    imageLink: COIN_IMAGE.BTC,
    symbol: 'BTC',
    chain: chainType.bitcoin,
    trcName: 'BTC',
    scan: 'https://www.blockchain.com/btc'
  },
  ether: {
    numChainId: 1,
    chainId: '0x1',
    numLoad: 1,
    isSupportedEIP1559: true,
    isToken: true,
    isSupportedNFT: true,

    trcToken: 'ERC20',
    nftToken: 'ERC721',
    balances: '0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6',
    multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: 'app_ethereum',
    id: 'ethereum',
    name: 'Ethereum',
    shortName: 'Ethereum',
    imageLink: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: chainType.ether,
    trcName: 'ETH ERC20 ERC721',
    rpcURL: 'https://nd-882-009-235.p2pify.com/f2cfb8777ba44e372c9ab251b51980d8',
    scan: 'https://etherscan.io'
  },
  binanceSmart: {
    numChainId: 56,
    chainId: '0x38',
    numLoad: 1,
    isToken: true,
    isSupportedNFT: true,
    nftToken: 'BEP721',
    trcToken: 'BEP20',
    symbolSpecial: 'BSC',
    balances: '0xA6762c710852681c4593C10c4304C5211FB2122c',
    multisend: '0x2E1D30460265bFEBedacf5bb6f9A80F0E74B7498',
    nftMint: '0xc4cAd0938256ABA4417c565044Be2c2EB77096cb',

    subName: 'BSC',

    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: 'app_binance',

    id: 'binancecoin',
    name: 'BNB Smart Chain',
    shortName: 'BSC',
    imageLink: COIN_IMAGE.BNB,
    symbol: 'BNB',
    chain: chainType.binanceSmart,
    trcName: 'BNB BEP20',
    rpcURL: 'https://bsc-mainnet.nodereal.io/v1/68ac333c4bc646df8ef23fe996dd6d83',
    scan: 'https://bscscan.com'
  },
  heco: {
    numChainId: 128,
    chainId: '0x80',
    numLoad: 1,
    isToken: true,
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    trcToken: 'HRC20',
    nftToken: 'HRC721',
    isWeb3: true,
    isFee: true,
    image: 'app_heco',
    balances: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',

    id: 'huobi-token',
    name: 'HECO Chain',
    shortName: 'Huobi',
    imageLink: COIN_IMAGE.HT,
    symbol: 'HT',
    chain: chainType.heco,
    trcName: 'HT HRC20',
    rpcURL: 'https://http-mainnet.hecochain.com',
    scan: 'https://hecoinfo.com'
  },
  okex: {
    numChainId: 66,
    chainId: '0x42',
    numLoad: 2,
    isSupportedNFT: true,
    balances: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multisend: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    isToken: true,
    id: 'okexchain',
    name: 'OKExChain',
    image: 'app_okex',
    symbol: 'OKT',
    chain: chainType.okex,
    imageLink: COIN_IMAGE.OKT,
    icon: 'okex',
    trcToken: 'KIP20',
    nftToken: 'NFT',
    trcName: 'OKT KIP10 KIP20 NFT',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://exchainrpc.okex.org',
    scan: 'https://www.oklink.com/okexchain'
  },
  gate: {
    numChainId: 86,
    chainId: '0x56',
    numLoad: 2,
    balances: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multisend: '0x963e1bcd1f82724bd8fa16a3b6962d100fb287fc',
    nftMint: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',
    isSupportedNFT: true,
    isToken: true,
    id: 'gatechain-token',
    name: 'GateChain',
    image: 'app_gate',
    symbol: 'GT',
    chain: chainType.gate,
    imageLink: COIN_IMAGE.GT,
    icon: 'gate',
    trcToken: 'GRC20',
    nftToken: 'GRC721',
    trcName: 'GT GRC20 GRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://evm.gatenode.cc',
    scan: 'https://gatescan.org'
  },

  kucoin: {
    numChainId: 321,
    chainId: '0x141',

    numLoad: 2,
    isToken: true,
    subName: 'KCS',
    trcToken: 'KRC20',
    nftToken: 'KRC721',
    balances: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    isWeb3: true,
    isSupportedNFT: true,
    isFee: true,
    image: 'app_kucoin',
    id: 'kucoin-shares',
    name: 'KuCoin Chain',
    shortName: 'Kucoin',
    imageLink: COIN_IMAGE.KCS,
    symbol: 'KCS',
    chain: chainType.kucoin,
    trcName: 'KCS KRC20 KRC721',
    rpcURL: 'https://rpc-mainnet.kcc.network',
    scan: 'https://explorer.kcc.io/en'
  },
  solana: {
    numLoad: 1,
    isToken: true,
    trcToken: 'SPL',
    nftToken: 'SPL NFT',
    multisend: true,
    isSupportedNFT: true,

    image: 'app_solana',

    id: 'solana',
    name: 'Solana',
    shortName: 'Solana',
    imageLink: COIN_IMAGE.SOL,
    symbol: 'SOL',
    chain: chainType.solana,
    trcName: 'SOL SPL',
    rpcURL: 'https://orca.rpcpool.com',
    rpcURLSerum: 'https://solana-api.projectserum.com',
    scan: 'https://solscan.io'
  },
  near: {
    numLoad: 2,
    isToken: true,
    trcToken: 'NEP21',

    image: 'app_near',
    id: 'near',
    name: 'Near',
    imageLink: COIN_IMAGE.NEAR,
    symbol: 'NEAR',
    trcName: 'NEAR NEP21',
    chain: chainType.near,
    scan: 'https://explorer.near.org',
    rpcURL: 'https://public-rpc.blockpi.io/http/near',
    scanTxs: 'transactions',
    scanAddr: 'accounts'
  },
  avax: {
    numPath: 9000,

    numChainId: 43114,
    chainId: '0xa86a',

    numLoad: 1,
    isSupportedNFT: true,
    isToken: true,
    trcToken: 'ARC20',
    nftToken: 'ARC721',
    symbolSpecial: 'CCHAIN',
    balances: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multisend: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    nftMint: '0x0eCE57A677D5e72D1ad45774239e23463CF1d743',

    subName: 'C',

    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    image: 'app_avalancher',
    id: 'avalanche-2',
    name: 'Avalanche C-Chain',
    shortName: 'Avalanche',
    imageLink: COIN_IMAGE.AVAX,
    symbol: 'AVAX',
    chain: chainType.avax,
    trcName: 'AVAX-C ARC20',
    rpcURL: 'https://rpc.ankr.com/avalanche',
    scan: 'https://snowtrace.io'
  },
  avaxX: {
    numLoad: 5,
    symbolSpecial: 'XCHAIN',
    subName: 'X',
    image: 'app_avalancher',
    id: 'avalanche-2',
    name: 'Avalanche X-Chain',
    shortName: 'Avalanche',
    imageLink: COIN_IMAGE.AVAX,
    symbol: 'AVAX',
    chain: chainType.avaxX,
    trcName: 'AVAX-X',
    scan: 'https://avascan.info/blockchain/x'
  },
  tron: {
    numLoad: 1,
    isToken: true,
    trcToken: 'TRC20',
    trcSubName: 'TRC10',

    image: 'app_tron',

    id: 'tron',
    name: 'Tron',
    shortName: 'Tron',
    imageLink: COIN_IMAGE.TRX,
    symbol: 'TRX',
    chain: chainType.tron,
    trcName: 'TRX TRC10 TRC20',
    scan: 'https://tronscan.org/#',
    scanTxs: 'transaction'
  },
  matic: {
    numChainId: 137,
    chainId: '0x89',
    numLoad: 2,
    isToken: true,
    trcToken: 'PRC20',
    nftToken: 'PRC721',
    isSupportedV2: true,
    isSupportedNFT: true,
    isFee: true,
    isWeb3: true,
    balances: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multisend: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',
    nftMint: '0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E',

    id: 'matic-network',
    name: 'Polygon',
    image: 'app_polygon',
    imageLink: COIN_IMAGE.MATIC,
    symbol: 'MATIC',
    chain: chainType.matic,
    trcName: 'MATIC PRC20',
    rpcURL: 'https://nd-302-286-039.p2pify.com/2d8e16206109f7b5256e1d7d58345a90',
    scan: 'https://polygonscan.com'
  },
  fantom: {
    numChainId: 250,
    chainId: '0xFA',

    numLoad: 2,
    isSupportedV2: true,
    isToken: true,
    isSupportedNFT: true,
    trcToken: 'FRC20',
    nftToken: 'FRC721',
    balances: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multisend: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    nftMint: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',

    isFee: true,
    isWeb3: true,

    id: 'fantom',
    name: 'Fantom',
    image: 'app_fantom',
    imageLink: COIN_IMAGE.FTM,
    symbol: 'FTM',
    chain: chainType.fantom,
    trcName: 'FANTOM FRC20',
    rpcURL: 'https://rpc.ftm.tools',
    scan: 'https://ftmscan.com'
  },
  xDai: {
    numChainId: 100,
    chainId: '0x64',

    numLoad: 2,
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    isSupportedNFT: true,
    isToken: true,
    id: 'xdai',
    name: 'xDAI Chain',
    image: 'app_xDai',
    symbol: 'XDAI',
    chain: chainType.xDai,
    imageLink: COIN_IMAGE.XDAI,
    icon: 'xDai',
    trcToken: 'XRC20',
    nftToken: 'XRC721',
    trcName: 'XDAI XRC20',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://rpc.xdaichain.com',
    scan: 'https://blockscout.com/xdai/mainnet'
  },
  polkadot: {
    isPolkadot: true,
    numLoad: 3,
    image: 'app_polkadot',

    isMnemonic: true,
    id: 'polkadot',
    name: 'Polkadot',
    shortName: 'Polkadot',
    imageLink: COIN_IMAGE.DOT,
    symbol: 'DOT',
    chain: chainType.polkadot,
    trcName: 'DOT',
    rpcURL: 'rpc.polkadot.io',
    scan: 'https://polkadot.subscan.io',
    scanTxs: 'extrinsic',
    scanAddr: 'account'
  },
  kusama: {
    isPolkadot: true,
    numLoad: 3,
    image: 'app_kusama',

    isMnemonic: true,
    id: 'kusama',
    name: 'Kusama',
    shortName: 'Kusama',
    imageLink: COIN_IMAGE.KSM,
    symbol: 'KSM',
    chain: chainType.kusama,
    trcName: 'KSM',
    rpcURL: 'kusama-rpc.polkadot.io',
    scan: 'https://kusama.subscan.io'
  },
  cosmos: {
    prefix: 'cosmos',
    numPath: 118,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    id: 'cosmos',
    name: 'Cosmos',
    image: 'app_cosmos',
    symbol: 'ATOM',
    imageLink: COIN_IMAGE.ATOM,
    chain: chainType.cosmos,
    trcName: 'ATOM',
    scan: 'https://www.mintscan.io/cosmos',
    scanTxs: 'txs',
    scanAddr: 'account',
    scanBlocks: 'blocks/id'
  },
  thor: {
    prefix: 'thor',
    numPath: 931,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    id: 'thorchain',
    name: 'THORChain',
    image: 'app_thorchain',
    imageLink: COIN_IMAGE.RUNE,
    symbol: 'RUNE',
    chain: chainType.thor,
    trcName: 'RUNE',
    scan: 'https://viewblock.io/thorchain'
  },
  terra: {
    prefix: 'terra',
    numPath: 330,

    numLoad: 3,
    isToken: true,
    trcToken: 'CW20',

    isCosmos: true,
    isMemo: true,

    id: 'terra-luna',
    name: 'Terra',
    image: 'app_terra',
    symbol: 'LUNA',
    denom: 'uluna',
    imageLink: COIN_IMAGE.LUNA,
    chain: chainType.terra,
    trcName: 'LUNA CW20',
    scan: 'https://finder.terra.money/columbus-4'
  },
  band: {
    prefix: 'band',
    numPath: 494,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,
    id: 'band-protocol',
    name: 'BandChain',
    image: 'app_band',
    imageLink: COIN_IMAGE.BAND,
    symbol: 'BAND',
    trcName: 'BAND',
    chain: chainType.band,
    scan: 'https://cosmoscan.io',
    scanAddr: 'account'
  },
  kava: {
    prefix: 'kava',
    numPath: 459,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,

    id: 'kava',
    name: 'Kava',
    image: 'app_kava',
    imageLink: COIN_IMAGE.KAVA,
    symbol: 'KAVA',
    chain: chainType.kava,
    trcName: 'KAVA',
    scan: 'https://www.mintscan.io/kava',
    scanTxs: 'txs',
    scanAddr: 'account',
    scanBlocks: 'blocks/id'
  },
  secretNetwork: {
    prefix: 'secret',
    numPath: 529,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,

    id: 'secret',
    name: 'Secret Network',
    image: 'app_secret_network',
    imageLink: COIN_IMAGE.SCRT,
    symbol: 'SCRT',
    chain: chainType.secretNetwork,
    trcName: 'SCRT',
    scan: 'https://secretnodes.com/secret/chains/secret-4',
    scanTxs: 'transactions',
    scanAddr: 'account',
    scanBlocks: 'blocks/id'
  },
  persistence: {
    prefix: 'persistence',
    numPath: 750,

    numLoad: 3,
    isCosmos: true,
    isMemo: true,

    id: 'persistence',
    name: 'Persistence',
    image: 'app_-persistence',
    imageLink: COIN_IMAGE.XPRT,
    symbol: 'XPRT',
    chain: chainType.persistence,
    trcName: 'XPRT',
    scan: 'https://explorer.persistence.one',
    scanBlocks: 'blocks',
    scanTxs: 'transactions',
    scanAddr: 'wallet'
  },

  binance: {
    prefix: 'bnb',
    numPath: 714,

    numLoad: 2,
    isToken: true,
    trcToken: 'BEP2',
    symbolSpecial: 'BC',

    isCosmos: true,
    isMemo: true,
    subName: 'BC',

    image: 'app_binance',

    id: 'binancecoin',
    name: 'Binance Chain',
    shortName: 'Binance',
    imageLink: COIN_IMAGE.BNB,
    symbol: 'BNB',
    chain: chainType.binance,
    trcName: 'BNB BEP2 BEP8',
    scan: 'https://explorer.binance.org'
  },
  // elrond: {
  //   prefix: 'erd',
  //   numPath: 508,
  //   nftToken: 'SFT',
  //   numLoad: 3,
  //   isToken: true,
  //   trcToken: 'ESDT',

  //   id: 'elrond-erd-2',
  //   name: 'Elrond',
  //   image: 'app_elrond',
  //   imageLink: COIN_IMAGE.EGLD,
  //   symbol: 'EGLD',
  //   chain: chainType.elrond,
  //   trcName: 'EGLD ESDT SFT',
  //   scan: 'https://explorer.elrond.com',
  //   scanTxs: 'transactions',
  //   scanAddr: 'accounts',
  //   scanBlocks: 'blocks'
  // },
  // tezos: {
  //   prefix: 'tz1',
  //   numPath: 1729,
  //   nftToken: 'FA2',
  //   isToken: true,
  //   trcToken: 'FA1.2',
  //   numLoad: 1,

  //   id: 'tezos',
  //   name: 'Tezos',
  //   image: 'app_tezos',
  //   imageLink: COIN_IMAGE.XTZ,
  //   symbol: 'XTZ',
  //   chain: chainType.tezos,
  //   trcName: 'XTZ FA1.2 FA2',
  //   scan: 'https://tezblock.io',
  //   scanTxs: 'transaction',
  //   scanAddr: 'account',
  //   scanBlocks: 'block'
  // },
  tomo: {
    numPath: 889,

    numChainId: 88,
    chainId: '0x58',
    // numChainId: 4,
    // chainId: '0x4',

    numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    trcToken: 'TRC21',
    nftToken: 'TRC721',
    isWeb3: true,
    isFee: true,
    image: 'app_tomochain',
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',

    id: 'tomochain',
    name: 'TomoChain',
    shortName: 'Tomo',
    imageLink: COIN_IMAGE.TOMO,
    symbol: 'TOMO',
    chain: chainType.tomo,
    trcName: 'TOMO TRC21',
    rpcURL: 'https://rpc.tomochain.com',
    scan: 'https://scan.tomochain.com'
  },
  kardia: {
    numChainId: 1,
    chainId: '0x0',

    numLoad: 2,
    isToken: true,
    id: 'kardiachain',
    name: 'KardiaChain',
    image: 'app_kardia',
    symbol: 'KAI',
    chain: chainType.kardia,
    imageLink: COIN_IMAGE.KAI,
    icon: 'kardia',
    subName: 'KAI',
    trcToken: 'KRC20',
    nftToken: 'KRC721',
    trcName: 'KAI KRC20 KRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://kai-seeds.kardiachain.io/',
    scan: 'https://explorer.kardiachain.io'
  },
  ronin: {
    prefix: 'ronin:',
    numChainId: 2020,
    chainId: '0x7e4',

    numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    id: 'ronin',
    name: 'Ronin',
    image: 'app_ronin',
    nftToken: 'RRC721',
    symbol: 'RON',
    chain: chainType.ronin,
    imageLink: COIN_IMAGE.RON,
    icon: 'ronin',
    trcToken: 'RRC20',
    trcName: 'RON RRC20 RRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://api.roninchain.com/rpc',
    scan: 'https://explorer.roninchain.com'
  },
  celo: {
    mainAddress: '0x471ece3750da237f93b8e339c536989b8978a438',
    numPath: 52752,

    numChainId: 42220,
    chainId: '0xA4EC',

    numLoad: 1,
    isSupportedNFT: true,
    isFee: true,
    isToken: true,
    balances: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multisend: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    isWeb3: true,
    nftToken: 'CELO721',
    image: 'app_celo',
    id: 'celo',
    name: 'Celo',
    shortName: 'Celo',
    imageLink: COIN_IMAGE.CELO,
    symbol: 'CELO',
    chain: chainType.celo,
    trcName: 'CELO CUSD',
    rpcURL: 'https://forno.celo.org',
    scan: 'https://explorer.celo.org'
  },
  klaytn: {
    numChainId: 8217,
    chainId: '0x2019',

    numLoad: 2,
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',

    isSupportedNFT: true,
    isToken: true,
    id: 'klay-token',
    name: 'Klaytn',
    image: 'app_klaytn',
    symbol: 'KLAY',
    trcToken: 'KIP7',
    nftToken: 'KIP37',

    chain: chainType.klaytn,
    imageLink: COIN_IMAGE.KLAY,
    icon: 'klaytn',
    trcName: 'KLAY KIP7 KIP37',
    isFee: true,
    isWeb3: true,
    scan: 'https://scope.klaytn.com',
    rpcURL: 'https://kaikas.cypress.klaytn.net:8651',
    scanAddr: 'account'
  },
  harmony: {
    prefix: 'one',
    numChainId: 1666600000,
    chainId: '0x63564C40',
    numLoad: 1,
    isToken: true,
    isSupportedNFT: true,
    nftToken: 'HRC721',
    trcToken: 'HRC20',
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    nftMint: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',

    isWeb3: true,
    isFee: true,
    image: 'app_harmony',

    id: 'harmony',
    name: 'Harmony',
    imageLink: COIN_IMAGE.ONE,
    symbol: 'ONE',
    chain: chainType.harmony,
    trcName: 'ONE HRC20 HRC721',
    rpcURL: 'https://api.harmony.one',
    scan: 'https://explorer.harmony.one'
  },
  // conflux: {
  //   prefix: 'cfx',
  //   trcToken: 'CRC20',
  //   nftToken: 'CRC721',
  //   isToken: true,
  //   isFee: true,
  //   numLoad: 1,

  //   id: 'conflux-token',
  //   name: 'Conflux',
  //   image: 'app_conflux',
  //   imageLink: COIN_IMAGE.CFX,
  //   symbol: 'CFX',
  //   chain: chainType.conflux,
  //   trcName: 'CFX CRC20 CRC721',
  //   scan: 'https://www.confluxscan.io',
  //   scanTxs: 'transaction',
  //   scanAddr: 'address',
  //   scanBlocks: 'block'
  // },
  //
  optimism: {
    defaultGas: 882000,
    mainAddress: '0x4200000000000000000000000000000000000006',
    isL2: true,
    numChainId: 10,
    chainId: '0xA',
    // numChainId: 69,
    // chainId: '0x45',

    numLoad: 2,
    isToken: true,
    trcToken: 'ERC20 OPT',
    nftToken: 'ERC721 OPT',
    // balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    image: 'app_optimism',
    id: 'ethereum',
    name: 'Optimism',
    shortName: 'Optimism',
    imageLink: COIN_IMAGE.OP,
    symbol: 'ETH',
    symbolSpecial: 'OP',
    chain: chainType.optimism,
    trcName: 'ETH ERC20 ERC721',
    rpcURL: 'https://mainnet.optimism.io',
    // rpcURL: 'https://kovan.optimism.io',
    scan: 'https://optimistic.etherscan.io'
  },
  boba: {
    // defaultGas: 80000000,
    // mainAddress: '0x4200000000000000000000000000000000000006',
    isL2: true,
    numChainId: 288,
    chainId: '0x120',
    // numChainId: 28,
    // chainId: '0x1C',

    numLoad: 2,
    isToken: true,
    trcToken: 'ERC20 BOBA',
    nftToken: 'ERC721 BOBA',
    // multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    image: 'app_boba',
    id: 'ethereum',
    name: 'Boba Network',
    shortName: 'Boba Network',
    imageLink: COIN_IMAGE.BOBA,
    symbol: 'ETH',
    symbolSpecial: 'BOBA',
    chain: chainType.boba,
    trcName: 'ETH ERC20 ERC721',
    rpcURL: 'https://mainnet.boba.network',
    scan: 'https://blockexplorer.boba.network'
  },
  arbitrum: {
    defaultGas: 7000000,
    isL2: true,
    numChainId: 42161,
    chainId: '0xA4B1',
    // numChainId: 421611,
    // chainId: '0x66EEB',

    numLoad: 2,
    isToken: true,
    trcToken: 'ERC20 ARB',
    nftToken: 'ERC721 ARB',
    // balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // multisend: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    image: 'app_arbitrum',
    id: 'ethereum',
    name: 'Arbitrum',
    shortName: 'Arbitrum',
    imageLink: COIN_IMAGE.ETHARB,
    symbol: 'ETH',
    symbolSpecial: 'ARB',
    chain: chainType.arbitrum,
    trcName: 'ETH ERC20 ERC721',
    rpcURL: 'https://arb1.arbitrum.io/rpc',
    // rpcURL: 'https://rinkeby.arbitrum.io/rpc',
    scan: 'https://arbiscan.io'
  },
  arbitrumXdai: {
    isL2: true,
    numChainId: 200,
    chainId: '0xC8',

    numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    trcToken: 'ERC20 AOX',
    nftToken: 'ERC721 AOX',
    balances: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    nftMint: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',

    isWeb3: true,
    isFee: true,
    image: 'app_arbitrum_xdai',
    id: 'xdai',
    name: 'Arbitrum on xDai',
    shortName: 'Arbitrum on xDai',
    imageLink: COIN_IMAGE.ETHA0X,
    symbol: 'XDAI',
    symbolSpecial: 'AOX',
    chain: chainType.arbitrumXdai,
    trcName: 'XDAI XRC20 XRC721',
    rpcURL: 'https://arbitrum.xdaichain.com',
    scan: 'https://blockscout.com/xdai/aox'
  }

}

export const CURRENCY_DATA = [
  'VND',
  'USD',
  'CNY',
  'JPY',
  'THB',
  'AUD',
  'BRL',
  'CAD',
  'CHF',
  'CLP',
  'CZK',
  'DKK',
  'EUR',
  'GBP',
  'HKD',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'ISK',
  'KRW',
  'MXN',
  'MYR',
  'NOK',
  'NZD',
  'PHP',
  'PKR',
  'PLN',
  'RUB',
  'SEK',
  'SGD',
  'TRY',
  'TWD',
  'ZAR'
]
